name: 'Assert Branch Naming Convention'
on: [pull_request] 

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          # Branch Name: prefix/module/comment (and issue number if required)
          allowed_prefixes: 'feature,bugfix,refactor'
          regex: '^[a-z]+\/(scanner|parser|symboltable|hashtable|ampl|cases|scripts)\/[a-z0-9]+(-[a-z0-9]+)*$'
          ignore: master
          min_length: 5
