name: 'Assert Branch Naming Convention'
on: [push, pull_request] 

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          # Branch Name: prefix/module/comment (and issue number if required)
          allowed_prefixes: 'feature,bugfix,refactor'
          regex: '(scanner|parser|symboltable|hashtable|ampl|scripts)\/[a-z]+(-[0-9])*$'
          ignore: master
          min_length: 5
          max_length: 20
